---
- name: Prepare
  hosts: all
  gather_facts: false
  become: true

  roles:
    - role: bootstrap
      bootstrap_wait_for_host: true
    - role: basetools
      vars:
        _basetools_packages:
          default:
            - ntpdate
          Debian:
            - net-tools
            - unzip
            - gzip
            - apt-transport-https
            - ntpdate
            - curl
            - wget
            - jq
            - git
            - dstat
            - strace
            - powertop
            - i7z
            - iperf
            - gnupg2
