---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/tests/yaml-int.yml
platforms:
  - name: "ansible-role-terraform-${image:-debian}-${tag:-buster}"
    image: "${namespace:-redbeard28}/${image:-debian}:${tag:-buster}"
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../resources/default.yml
    prepare: ../resources/prepare.yml
    # verify: ../resources/verify.yml
  lint:
    name: ansible-lint
scenario:
  name: default
  create_sequence:
    - destroy
    - dependency
    - create
    - prepare
  converge_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - create
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: testinfra
  directory: ../default/tests/
  lint:
    name: flake8
